package org.uengine.ui.list.exception;

public class ExceptionCode {
    public static String DATASOURCE_GET_NAMING_ERR = "22";
    public static String DATASOURCE_GET_ETC_ERR = "29";
    public static String EJB_GET_NAMING_ERR = "22";
    public static String EJB_GET_ETC_ERR = "22";
    public static String DATASOURCE_GET_CONNECTION_ERR = "21";
    public static String DAO_SQL_ERR = "SQLEXCEPTION";
    public static String DAO_LOGIC_ERR = "23";
    public static String DAO_GET_INIT_ERR = "23";
    public static String EJB_LOGIC_ERR = "23";
    public static String DEL_LOGIC_ERR = "23";
    public static String DEL_RMI_ERR = "22";
    public static String EJB_CREATE_ERR = "22";
    public static String EJB_CREATE_RMI_ERR = "22";
    public static String DATA_SAVE_ERR = "NOT_SAVE";
    public static String DATA_UPDATE_ERR = "NOT_UPDATE";
    public static String DATA_DELETE_ERR = "NOT_DELETE";
    public static String DATA_NOT_FOUND_ERR = "234";
    public static String DAO_NULL_POINT_ERR = "46";
    public static String MSG_NOT_REG_ERR = "61";
}
